{% set version = "4.0.3" %}
{% set sha256 = "34824864c062b0b3030ad78210db5ae6a3960dfb61d5b27562d6631774de0286" %}

package:
  name: widgetsnbextension
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - jupyter-packaging
  run:
    - python >=3.7

test:
  imports:
    - widgetsnbextension

about:
  home: http://ipython.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Interactive Widgets for Jupyter
  description: |
    Interactive Jupyter widgets for the classic Jupyter Notebook application.
  doc_url: https://pypi.python.org/pypi/widgetsnbextension
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/widgetsnbextension

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
    - ocefpaf
